version: '3.8'

services:
  # Next.js Application with embedded PostgreSQL database
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5432:5432"
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=saas_cms
      - POSTGRES_USER=saas_cms_user
      - POSTGRES_PASSWORD=saas_cms_password
      - DATABASE_URL=postgresql://saas_cms_user:saas_cms_password@localhost:5432/saas_cms
      - JWT_SECRET=your-jwt-secret-change-in-production
      - CLOUDINARY_CLOUD_NAME=your-cloudinary-cloud-name
      - CLOUDINARY_API_KEY=your-cloudinary-api-key
      - CLOUDINARY_API_SECRET=your-cloudinary-api-secret
      - GOOGLE_ANALYTICS_ID=your-google-analytics-id
      - GOOGLE_TAG_MANAGER_ID=your-google-tag-manager-id
    volumes:
      # Persist uploads
      - ./public/uploads:/app/public/uploads
      # Persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

  # Nginx Reverse Proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - production

networks:
  app-network:
    driver: bridge

volumes:
  database:
    driver: local
  uploads:
    driver: local
  logs:
    driver: local 