# fly.toml app configuration file generated for saas_cms on 2025-07-25T05:30:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "saas-cms"
primary_region = "iad"

[build]
  image = "azar84/saas_cms:latest"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Temporarily disabled health checks to allow app to start
# [[http_service.checks]]
#   grace_period = "60s"
#   interval = "30s"
#   method = "GET"
#   timeout = "10s"
#   path = "/"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  source = "saas_cms_data"
  destination = "/app/data" 