# fly.toml app configuration file for saas_cms with PostgreSQL
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "saas-cms"
primary_region = "iad"

[build]
  image = "azar84/saas_cms:latest"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOSTNAME = "0.0.0.0"
  POSTGRES_DB = "saas_cms"
  POSTGRES_USER = "saas_cms_user"
  POSTGRES_PASSWORD = "saas_cms_password"
  DATABASE_URL = "postgresql://saas_cms_user:saas_cms_password@localhost:5432/saas_cms"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/"

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[metrics]
  port = 9091
  path = "/metrics" 