#!/bin/bash

echo "🔑 BuiltWith API Key Setup"
echo "=========================="
echo ""
echo "To get real data from BuiltWith API, you need a valid API key."
echo ""
echo "1. Go to https://builtwith.com/api"
echo "2. Sign up for an API key"
echo "3. Replace the test key in your .env file"
echo ""
echo "Current API key in .env:"
grep BUILTWITH_API_KEY .env
echo ""
echo "To update it, edit your .env file and replace:"
echo "BUILTWITH_API_KEY=\"your_api_key_here\""
echo ""
echo "With your real API key:"
echo "BUILTWITH_API_KEY=\"your_real_api_key_here\""
echo ""
echo "After updating, restart the development server:"
echo "npm run dev"
