name: Deploy and Seed Database

on:
  push:
    branches: [ main, version-1.2 ]
  workflow_dispatch:

jobs:
  deploy-and-seed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy to Vercel
      run: |
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    - name: Wait for deployment
      run: sleep 30

    # Commented out seeding step since DEPLOY_URL secret is not configured
    # - name: Seed database
    #   run: |
    #     # Call the seed API endpoint
    #     curl -X POST ${{ secrets.DEPLOY_URL }}/api/admin/seed-database
    #   env:
    #     DEPLOY_URL: ${{ secrets.DEPLOY_URL }} 